### ISSUE TITLE
x,y,z to u,v for sphere

### ISSUE THREAD

**Issue by abishek-sundar** [dilevin/computer-graphics-meshes#14]
Does anybody know what the notation ||x|| means here? I've tried absolute value, but anytime x is less than z, acos returns nan...
![image](https://user-images.githubusercontent.com/41223420/53675983-94133f00-3c6a-11e9-920d-382cd58d4649.png)

**Comment by itsvismay** [comment]
Thats the norm of x.
![image](https://user-images.githubusercontent.com/2146596/53688137-c07b9980-3d04-11e9-8be7-e48a5750dc25.png)

**Comment by Justin-Yuan** [comment]
using ||r|| might be more clear (where r is the radius)
