### ISSUE TITLE
Design cube and sphere without any info?

### ISSUE THREAD

**Issue by triangleCZH** [dilevin/computer-graphics-meshes#15]
We are asked to build cube and sphere, but we don't have any information about coordinates.
Should I design all the coordinates, radius by myself?
It seems like, once the texture coordinates (in (u, v) plane) are correct, and the mapping from (x, y, z) to (u, v) is correct, the (x, y, z) coordinate values don't matter. Is that true?

**Comment by dilevin** [comment]
To be clear the vertex positions must be specify a cube and a square but the center of each object doesn’t matter.

**Comment by triangleCZH** [comment]
@dilevin Thank you for your reply! So as long as the cube and the sphere(Earth) show correctly in the viewer, it will be okay, is that correct?

**Comment by dilevin** [comment]
Correct
