### ISSUE TITLE
Resize giving runtime error (cube)

### ISSUE THREAD

**Issue by msnhao** [dilevin/computer-graphics-meshes#17]
The resize for matrix F seems to cause a runtime error:
Assertion failed: (i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols())),

Here's my code:
  V.resize(8,3);
  F.resize(6,4);
  UV.resize(14,2);
  UF.resize(6,4);
  NV.resize(6,3);
  NF.resize(6,4);
  return;

**Comment by Justin-Yuan** [comment]
i got the same error, did u end up solving it  :) ?
