### ISSUE TITLE
obj.cpp -> remove 'shared' from file path

### ISSUE THREAD

**Issue by ACalza** [dilevin/computer-graphics-meshes#2]
`set_texture_from_png("../shared/data/earth-square.png", v.viewer.data());`

-> `set_texture_from_png("../data/earth-square.png", v.viewer.data());`

Got stuck for an hour or so, but just a PSA if people are stuck on it.

**Comment by dilevin** [comment]
Shared is a sub module of this repo. Did you pull using the recursive flag ?

**Comment by ACalza** [comment]
Shared is empty when run with --recursive

**Comment by dilevin** [comment]
I made a video of me cutting and pasting the clone instructions from the README and installing the assignment.

The shared and shared/data directories contain the appropriate files.  This is on a MacBook Pro running OSX High Sierra.  Can you confirm that this exact sequence fails to properly create the shared directory. Please let me know what platform you are running the code on. 

[A5_Installation.mp4.zip](https://github.com/dilevin/computer-graphics-meshes/files/2863011/A5_Installation.mp4.zip)

**Comment by ACalza** [comment]
`➜  Developer git clone --recursive https://github.com/alecjacobson/computer-graphics-meshes.git
Cloning into 'computer-graphics-meshes'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 93 (delta 3), reused 20 (delta 3), pack-reused 65
Unpacking objects: 100% (93/93), done.
Submodule 'libigl' (https://github.com/libigl/libigl-legacy) registered for path 'libigl'
Submodule 'shared' (https://github.com/alecjacobson/computer-graphics-shared) registered for path 'shared'
Cloning into '/Users/albertcalzaretto/Developer/computer-graphics-meshes/libigl'...
remote: Enumerating objects: 40482, done.        
remote: Total 40482 (delta 0), reused 0 (delta 0), pack-reused 40482
Receiving objects: 100% (40482/40482), 342.88 MiB | 7.85 MiB/s, done.
Resolving deltas: 100% (26636/26636), done.
Cloning into '/Users/albertcalzaretto/Developer/computer-graphics-meshes/shared'...
remote: Enumerating objects: 30553, done.        
remote: Total 30553 (delta 0), reused 0 (delta 0), pack-reused 30553        
Receiving objects: 100% (30553/30553), 21.60 MiB | 7.50 MiB/s, done.
Resolving deltas: 100% (624/624), done.
error: Server does not allow request for unadvertised object 230df4d30b46ef4b7cd6ab68eb1c7e83cad7e09a
Fetched in submodule path 'libigl', but it did not contain 230df4d30b46ef4b7cd6ab68eb1c7e83cad7e09a. Direct fetching of that commit failed.
➜  Developer ls -a computer-graphics-meshes/shared 
.    ..   .git`

I used:

git clone --recursive https://github.com/alecjacobson/computer-graphics-meshes.git

rather than 

git clone --recursive https://github.com/dilevin/computer-graphics-meshes.git

Since it was initially in the readme
