### ISSUE TITLE
Does it matter which colour on the cube is displayed on start up?

### ISSUE THREAD

**Issue by Olivia-Roscoe** [dilevin/computer-graphics-meshes#20]
My cube looks completely normal, but always displays the yellow face at the start, does the initial colour matter (ie. does the green face have the be the front)? Because I imagine its just the order the faces are declared, and want to know if I should change them

**Comment by dilevin** [comment]
as long as the relative ordering is correct, this is fine (i.e the texture on the cube can be off by a rigid rotation but cannot be flipped or reflected)
