### ISSUE TITLE
Sphere projection format from notes

### ISSUE THREAD

**Issue by Olivia-Roscoe** [dilevin/computer-graphics-meshes#21]
For the sphere projection, the .h file says to use mercator projection. The textbook uses Miller. I was wondering what type of projection the notes use.

**Comment by songfeil** [comment]
If the .h file specifies mercator, please use mercator. Thanks!

**Comment by NPTP** [comment]
That still leaves the question: What type of projection is used in the notes? For reference, this is the one shown:
![image](https://user-images.githubusercontent.com/16977354/74985406-61c39a00-5405-11ea-9d87-c741d2dd7d00.png)

**Comment by dilevin** [comment]
It’s inverse spherical coordinates
