### ISSUE TITLE
How to handle the top/bottom (poles) of sphere in a quad mesh?

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-meshes#26]
Hi, question is mostly in the title. How do we have closed poles on each end of the sphere using only quads in sphere.cpp? As far as I can tell we need the poles to use triangles to create a watertight mesh. Do we simply duplicate one vertex of the quad at the poles to create the appearance triangles there?

Thanks!

**Comment by chenjas** [comment]
I believe multiple points of a quad can be the same vertex.
Another possibility for simplicity is defining multiple vertices that occupy the same geometric position for the poles.
