### ISSUE TITLE
Average of vectors

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-meshes#30]
Hi,
Just want to verify that computing the "average" of vectors is just simple addition of n vectors then multiplying the result by 1/n? And since no normalization took place, this would result in an average vector which is weighted by the magnitudes of each of the n vectors, right?

Thanks!

**Comment by songfeil** [comment]
If vector represents direction, then you can just simply add up and normalize the result. 

If it represents position, then “average” probably means linear interpolation of the input vectors.
