### ISSUE TITLE
Inconsistent light reflection on cube

### ISSUE THREAD

**Issue by Jiogit** [dilevin/computer-graphics-meshes#33]
My cube seems to work correctly, but for certain colours, the light reflection (circle of light on the surface) is not visible
It is visible on other colours
Is this normal?

**Comment by songfeil** [comment]
No, check your normals.

**Comment by Jiogit** [comment]
After closely looking, the circle seems to be present for my red, yellow and white sides too
The lines narrow as if there is a circle there when moving the cube around
The circle is not visible as with the other coloured surfaces though
Is this acceptable?

**Comment by songfeil** [comment]
Emm haven't quite met that before. Could you please upload a screenshot?

**Comment by Jiogit** [comment]
![orangecube](https://user-images.githubusercontent.com/43357169/75100402-1642f480-559b-11ea-9cde-d4d72bec10ee.png)
![redcube](https://user-images.githubusercontent.com/43357169/75100403-180cb800-559b-11ea-9e3a-e5bc1ea875d0.png)
Notice how the red surface does not have the light present, but the lines (near the bottom) narrow like the ones on the orange surface as if the light was there

**Comment by songfeil** [comment]
That looks fine. No worries.

**Comment by Jiogit** [comment]
Thanks for the clarification
