### ISSUE TITLE
cube missing parts?

### ISSUE THREAD

**Issue by Leuxll** [dilevin/computer-graphics-meshes#44]
Hello, my cube is missing a triangle. Does anyone happen to know why this might be happening? Also, the lighting seems a bit off, does that matter?
<img width="709" alt="Screenshot 2023-10-18 at 12 56 36 PM" src="https://github.com/dilevin/computer-graphics-meshes/assets/69574944/37a6d8eb-8315-4f2c-b740-ad83764eb633">

**Comment by Zhecheng-Wang** [comment]
You can see there are edges crossing another edge (see the "x" shadow lines on the yellow face).

Your F is wrong so you are connecting the wrong vertices, think about how you should connect the vertices for one cube side.

**Comment by Leuxll** [comment]
ahhh yes, i got it now. Thank you very much!
