### ISSUE TITLE
Cannot understand Cube Texture

### ISSUE THREAD

**Issue by jarenworme** [dilevin/computer-graphics-meshes#49]
I cannot understand what I am misunderstanding about this, can someone let me know what I am doing wrong that my textures are not showing up? From all the resources I could find this is how the obj file is supposed to look..

![cubeChart](https://github.com/dilevin/computer-graphics-meshes/assets/90414176/6b1a2deb-be1c-41f2-acc2-aef38e817c9a)
![cubeObjFile](https://github.com/dilevin/computer-graphics-meshes/assets/90414176/3fac0cbc-4c20-40f1-b530-a77568a26186)
![malformedCube](https://github.com/dilevin/computer-graphics-meshes/assets/90414176/10484c14-d908-4c0f-81ce-7bb15067e7c1)

**Comment by Zhecheng-Wang** [comment]
It looks like your face might be inverted -- in addition, I think your face is having the same issue in #44.
Can you double-check your face matrix?

I think you are following your vertex ordering in the write-up, which will make the face intersect with itself and invert the face orientation.

**Comment by jarenworme** [comment]
Why would that cause the face to intersect itself? Is there a certain order I need to define the faces in??

**Comment by Zhecheng-Wang** [comment]
Because the face is connecting vertices following the **order** of the vertex indices. Connecting vertices in the order of 1/2/3/4 and 2/1/4/3 -> two different topologies.

Think of 4 points in space, now you need to connect them to make a quad with one stroke. You certainly wouldn't want to connect them across the diagonal. The shining line on the left face of the cube in your image implies your face is connected in the wrong order.

**Comment by jarenworme** [comment]
Ok I traced through all the faces and made sure to align their vertices sequentially, but still no luck with the texture. It wraps around half the cube and is black. Any other suggestions?
![Screenshot 2023-10-24 174855](https://github.com/dilevin/computer-graphics-meshes/assets/90414176/dfde057f-544d-4016-aab0-52d59400fca6)
![Screenshot 2023-10-24 175054](https://github.com/dilevin/computer-graphics-meshes/assets/90414176/b8ed0f01-8c9d-4e3b-8098-bf2de02bd690)

**Comment by Zhecheng-Wang** [comment]
I think your NV might also be wrong -- here is what I get when I inverted all the NV but one row, as you can see the shading can't shine on the faces with the wrong normal.
![image](https://github.com/dilevin/computer-graphics-meshes/assets/50251021/92046993-0b6b-4107-82f6-189d61a51dc6)
I think your UV is on the right track. I would suspect it is a UF issue.

**Comment by jarenworme** [comment]
The issue was that the cube was not accessing the texture file. It was correct since the last post. Since I am on windows, I had to change the file path to include an extra ../ since the code is in the debug folder.
