### ISSUE TITLE
Catmull-clark

### ISSUE THREAD

**Issue by AllenLXL** [dilevin/computer-graphics-meshes#5]
Handout said we're deal with **pure quad** mesh. What assumption can we made on **pure quad** mesh? I thought in that case each vertex can only have 4 neighbour faces and vertices, but it's not. Also from visualization, there are triangular meshes... And we can see there is one vertex has 5 neighbour vertices...
<img width="436" alt="pasted graphic" src="https://user-images.githubusercontent.com/25393564/53126553-64f42380-352e-11e9-83a7-9c118d810614.png">

**Comment by abedef** [comment]
I am also wondering about this. I just finished implementing my function with the *pure quad mesh* assumption and it falls apart around the areas with the awkward face connections (mainly around the seams splitting the model in two down the middle). Any thoughts on how to work around this? Which assumptions **can** we make?
