### ISSUE TITLE
Catmull Clark issue with the duck

### ISSUE THREAD

**Issue by johnnyjly** [dilevin/computer-graphics-meshes#51]
Hi. 
I don't know why but I always receive `free(): invalid next size (normal)` when running with the bob.obj. 
However, everything works fine if I switch to the cube. I'm working on WSL2 using VcXsrv for the display.

![image](https://github.com/dilevin/computer-graphics-meshes/assets/48067740/ba154d02-c77c-4059-a1b5-29d33480792c)
![image](https://github.com/dilevin/computer-graphics-meshes/assets/48067740/9018f0b8-fd00-4809-b259-0e70c95ec1ec)
![image](https://github.com/dilevin/computer-graphics-meshes/assets/48067740/d35105d5-dabc-4d2f-81ee-0499e1e8800a)

The duck does show up but whenever I press the space I receive the error.
Is that anything wrong in my code? Or can I safely assume that my code (for the assignment) is correct but there might be something wrong with the glfw or x11 forwarding (I had some issues with these 2 before).

**Comment by johnnyjly** [comment]
Add-on:
I tried to add some print statements within my code, and it shows that it does go into my loop and do the job, but raise the free() error when it is going out of the loop. So I tried to remove the loop (ignore the num_iterations) but it still doesn't work.

**Comment by Zhecheng-Wang** [comment]
Since you are WSL, please run gdb.
do `gdb ./quad_subdivision` and then `r` to run.
use command `bt` to print the stack trace leads to the error.

**Comment by johnnyjly** [comment]
Thanks for your comment. 
Actually I realized right after I posted this issue that there is a mistake in the size of a matrix, which leads to the corruption.
