### ISSUE TITLE
Catmull Clark Efficiency

### ISSUE THREAD

**Issue by AlekseyPanas** [dilevin/computer-graphics-meshes#57]
How efficient does the algorithm need to be? Mine runs pretty slow for bob the duck on the 4th iteration, taking roughly 20-30 seconds

**Comment by Zhecheng-Wang** [comment]
Did you build in release?

**Comment by AlekseyPanas** [comment]
Oh thats right, I forgot about that 😆

**Comment by AlekseyPanas** [comment]
It takes roughly 2-3 seconds in release mode, so I figure thats okay
