### ISSUE TITLE
Texture doesn't get applied properly to the cube

### ISSUE THREAD

**Issue by alexei-zolotarevschi** [dilevin/computer-graphics-meshes#7]
![untitled](https://user-images.githubusercontent.com/15279316/53196786-37bb7a00-35ef-11e9-9fba-24cf48af8b94.png)
I'm probably not getting my UV and UF right, but I've tried various approaches and they all result in the same thing.

**Comment by dilevin** [comment]
You are applying the whole texture to each face of your cube. Think about how to choose UV to map each single colour square in the cross pattern to a different face in the cube.

**Comment by alexei-zolotarevschi** [comment]
Figured it out. One of my approaches was correct, but in some places I was using fractions like 1/2 instead of 0.5, and for some reason it wasn't happy with it.
