### ISSUE TITLE
Catmull Clark strange bug

### ISSUE THREAD

**Issue by milomg** [dilevin/computer-graphics-meshes#70]
Similar to #24, I occasionally get rectangles that are wildly offset, while the rest looks fine.

<img width="1392" alt="Screenshot 2024-10-20 at 4 24 35 AM" src="https://github.com/user-attachments/assets/26d95166-e4a3-407d-993e-ad8ff77b2ad8">

It seems like this happens more frequently if I press space in the middle of a drag rotation, which makes it seem like there are two concurrent threads causing a dual write (also usually easier to trigger in debug mode and/or running through a debugger to slow the program down). Is this memory issue because of quad_subdivision.cpp/igl or should I be doing something in catmull_clark to prevent this?

**Comment by burneracc0112** [comment]
perhaps try to narrow down the issue by modifying main so that you load the mesh, perform a few iterations of the algorithm, and THEN load up this new mesh in the viewer.

That should tell you whether interacting with the viewer could be causing the issue, however unlikely that is.

**Comment by milomg** [comment]
Finally managed to get valgrind to track origins by rebuilding on linux instead of mac. The issue was calling `+=` on a matrix that hadn't been initialized to 0
