### ISSUE TITLE
Do we need to have the minimum amount of vertices for max marks?

### ISSUE THREAD

**Issue by WChrisK** [dilevin/computer-graphics-meshes#8]
This isn't a problem for the cube, but even though I have the globe working perfectly... there's some extra vertices that could be compressed (ex: the top point on the globe could really just be one vertex instead of a bunch of them being at the same point, you can probably guess what I did).

Is it acceptable for me to leave it like this, or do I need to make sure that I have the minimum amount of "indexable" (is this a word?) components as possible? It renders flawlessly if that means anything.

**Comment by harrychy8** [comment]
I tried to do it, but it was too difficult (i.e. too many corner cases). I guess just leave it like that?
