### ISSUE TITLE
Question with per corner normal

### ISSUE THREAD

**Issue by harrychy8** [dilevin/computer-graphics-meshes#9]
Can someone please explain to me how does the corner threshold work? I understand the concept is that we ignore faces where their normal is very different from the current face, but how do we use that 20 in the assignment? I have tried this, but it does not work (exactly the same as per-vertex normal).
![capture](https://user-images.githubusercontent.com/15678482/53208421-a3f4a880-3604-11e9-8799-19bbab95bf37.PNG)

**Comment by AllenLXL** [comment]
From the header file, we know ```corner_threshold``` is ```corner_threshold  threshold in degrees on sharp angles```.So I believe corner_threshold is an angle threshold to determine if two vectors differ a lot. Besides, suppose we have two normal vector ```A and B```, then we know ```A.dot(B) == 1 * 1 * cos(theta)```. The rest details should be easy.

**Comment by harrychy8** [comment]
Thank you
